env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/rport
builds:
  - id: rport
    main: ./cmd/rport
    binary: rport
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386
      # TODO: remove when https://github.com/go-ole/go-ole/issues/202 will be fixed
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
  - id: rportd
    main: ./cmd/rportd
    binary: rportd
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/share.BuildVersion={{.Version}}"
      #- "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: rport-only
    name_template: "rport_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - rport
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - rport.example.conf
  - id: rportd-only
    name_template: "rportd_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - rportd
    replacements:
      linux: Linux
      amd64: x86_64
    files:
      - rportd.example.conf
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: cloudradar-monitoring
    name: rport
  draft: true
  prerelease: true
